name: chatglobe
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.9.1
  image_picker: ^0.8.7+5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  go_router: ^7.0.1
  intl: ^0.18.1
  language_picker: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
